# Test info domain where hosts attribute is set to something invalid
template: info-domain.tt

vars:
  domain_name: cheese123.co.te
  hosts: blah
  pw:

output_assertions:
  count:
  match:
    - [ '//epp:reason', 'XML validation error at /epp/command/info/domain:info; ''blah'' does not meet schema requirements for hostsType', 'EPP: correct reason' ]
  match_all:
  attr_is:
    - [ '//epp:result', 'code', 2001, 'EPP: command failed' ]
